- package.json
- src/index.js
- test/__snapshots__/mount.test.js.snap
- test/__snapshots__/render.test.js.snap
- test/__snapshots__/shallow.test.js.snap
- test/fixtures/class.js
- test/fixtures/pure-function.js
- test/mount.test.js
> Fixed the root component of an element not being rendered

- package.json
This allows test to run correctly.
> Add missing package babel-jest

- src/index.js
- test/__snapshots__/shallow.test.js.snap
- test/shallow.test.js
> fix: Fixed shallowToJson when a component doesn't have a rendered component

- package.json
- src/index.js
- test/__snapshots__/mount.test.js.snap
- test/fixtures/class.js
- test/mount.test.js
> Fixed a bug where instrumentation code shows up in the snapshot output

- src/shallow.js
- test/__snapshots__/shallow.test.js.snap
- test/fixtures/class.js
- test/shallow.test.js
Fix for https://github.com/adriantoine/enzyme-to-json/issues/20
> Don't break when a component returns null

- package.json
- src/mount.js
- src/render.js
- src/shallow.js
- src/utils.js
- tests/core/__snapshots__/mount.test.js.snap
- tests/core/fixtures/pure-function.js
- tests/core/mount.test.js
- yarn.lock
> Replaced lodash.compact by another solution to keep 0 values

- package.json
- src/shallow.js
- tests/core/__snapshots__/shallow.test.js.snap
- tests/core/shallow.test.js
```
<Overlay
animation={false}
container={<SchedulePicker />}
placement="right"
rootClose={false}
show={false}
>
<strong>
Basic
</strong>
</Overlay>
```
otherwise it would be
```
<Overlay
animation={false}
container={
SchedulePicker {
"_reactInternalInstance": ShallowComponentWrapper {
"_calledComponentWillUnmount": false,
"_compositeType": 0,
"_context": Object {},
"_currentElement": <SchedulePicker />,
"_debugID": 21,
"_hostContainerInfo": null,
"_hostParent": null,
"_instance": [Circular],
"_mountOrder": 11,
"_pendingCallbacks": null,
"_pendingElement": null,
"_pendingForceUpdate": false,
"_pendingReplaceState": false,
"_pendingStateQueue": null,
"_renderedComponent": NoopInternalComponent {
"_currentElement": <Overlay
animation={false}
container={[Circular]}
onHide={undefined} …
```
> fix problem with `ShallowComponentWrapper` and `_reactInternalInstance`

- src/shallow.js
- tests/core/__snapshots__/shallow.test.js.snap
- tests/core/fixtures/class.js
- tests/core/shallow.test.js
> use .getNode and .getNodes if available for implicit updates

- .babelrc
- .travis.yml
- package-lock.json
- package.json
- tests/serializer/package-lock.json
- tests/serializer/package.json
> Reintroduced Node 4 support

- README.md
- index.d.ts
- src/createSerializer.js
- src/index.js
- src/serializer.js
- tests/__snapshots__/createSerializer-deep.test.js.snap
- tests/__snapshots__/createSerializer-shallow.test.js.snap
- tests/createSerializer-deep.test.js
- tests/createSerializer-shallow.test.js
This is an alternative to #69.
> Add createSerializer

- src/mount.js
- tests/__snapshots__/mount.test.js.snap
- tests/__snapshots__/shallow.test.js.snap
- tests/createSerializer-deep.test.js
- tests/createSerializer-shallow.test.js
- tests/mount.test.js
- tests/shallow.test.js
> Fixed flaky tests by providing more sensible test cases

- src/shallow.js
- tests/__snapshots__/mount.test.js.snap
- tests/__snapshots__/shallow.test.js.snap
- tests/fixtures/pure-function.js
- tests/mount.test.js
- tests/shallow.test.js
> Handle case where a componenent would expicitely return false in render

- index.d.ts
All I've done is make the typescript definition file match the actual javascript wrt what is exported
> Export function declarations in definitions file

- index.d.ts
Add Cheerio wrapper as accepted toJson input
> fix: correct toJson typings

- index.d.ts
See Issue https://github.com/adriantoine/enzyme-to-json/issues/115
> Make parameter noKey optional

- package.json
> chore: update enzyme peer dependency version

- docs/map.md
Hi @adriantoine 
Thanks for this really useful lib. I'd like to help with the docs of the mapping feature that just recently saved my day. 
Of course, things can be improved later but I think having something like this instead of _coming soon_ could help others knowing this awesome `map` feature.
> Initial documentation with example of Output mapping feature

- package.json
- src/utils.js
- tests/utils.test.js
- yarn.lock
Reverts adriantoine/enzyme-to-json#145
> Revert "Fix check of node type "

- package.json
- yarn.lock
Upgraded lodash with high severity security bug fixes:
For more information check: 
- https://github.com/lodash/lodash/wiki/Changelog
- https://snyk.io/test/npm/lodash/4.17.4
> upgrade lodash with security fixes

- index.d.ts
- package.json
- yarn.lock
Fix cheerio types following changes in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46006
Also fix #155
> fix(): fix cherio types following DT changes
