package.json
Travis is already setup to test with Node.js v4, however, the node
engine property in package.json requests Node v6. npm will log a warning
when it encounters an engine property that doesn't match, but yarn will
fail the install.
=> Relax required Node version to include Node v4

package.json, src/shallow.js, test/__snapshots__/shallow.test.js.snap, test/shallow.test.js
Currently React elements in props other than children aren't processed so snapshots will end up with `toString()`ed component types.
This is a breaking change for those with existing snapshots of elements containing elements in non-children props.
=> Handle elements in non-children props in shallow render

README.md, test/examples.test.js
This small change is off the main point of the example code :)
However, while learning React, I have often followed even small details of clearly-written examples like this without clearly understanding what I was doing. If I understand correctly, a function argument is now the public recommendation when next state depends on previous state:
https://facebook.github.io/react/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous
=> docs: Rewrite setState with function argument in first example

src/mount.js, tests/core/__snapshots__/mount.test.js.snap, tests/core/mount.test.js
=> Fix mountToJson not rendering mixed children

src/render.js, tests/core/__snapshots__/mount.test.js.snap, tests/core/__snapshots__/render.test.js.snap, tests/core/mount.test.js, tests/core/render.test.js
* Return an explicit `null` value instead of implicit `undefined` value so that `renderToJson` is consistent with `shallowToJson`
* Added test for `renderToJson` (and also for `mountToJson` to assert its behavior) compare to https://github.com/adriantoine/enzyme-to-json/blob/master/tests/core/shallow.test.js#L36-L41
=> renderToJson return null when a component returns null

package.json
I updated the peer dependency to the current jest version (v2.7.1) and reran the tests. Since all tests successfully passed I think it's safe to update the dependency.
=> Update enzyme peer dependency to v2.7.1

package.json, src/mount.js, src/render.js, src/shallow.js, tests/core/__snapshots__/mount.test.js.snap, tests/core/__snapshots__/render.test.js.snap, tests/core/__snapshots__/shallow.test.js.snap, tests/core/mount.test.js, tests/core/render.test.js, tests/core/shallow.test.js
This will allow multiple nodes to be rendered to JSON if they are received as a result of `find`.
Fixes #40
=> allow multiple nodes to be rendered to JSON

README.md
Describe an alternative when people cannot or prefer not to modify Jest configuration.
=> docs: Describe expect.addSnapshotSerializer in Jest 19 or higher

README.md
http://facebook.github.io/jest/blog/2017/02/21/jest-19-immersive-watch-mode-test-platform-improvements.html#snapshot-updates
> We dropped the “test” prefix in snapshot names from top level test or it calls.
> We improved the printing of React elements to cause less changes when the last prop in an element changes.
=> docs: Update snapshot examples to Jest 19

package-lock.json, package.json, src/mount.js, src/render.js, src/shallow.js, src/utils.js, tests/fixtures/match-object.js, tests/mount.test.js, tests/render.test.js, tests/shallow.test.js
[Standalone lodash packages are deprecated](https://github.com/lodash/lodash/issues/3361). The recommended way is to import functions from the main package instead.
=> Use the primary lodash package

index.d.ts
Because typescript compiler will fail because of implicit any type.
=> Fixed typescript implicit any type

src/mount.js, tests/__snapshots__/mount-deep.test.js.snap, tests/mount-deep.test.js
Currently if I try to mount a component that returns an array with a mode set to `deep` I get `<undefined/>`. This PR fixes it.
=> Fix deep mounting of arrays

src/mount.js, src/render.js, src/shallow.js
This fixes #82.
Basically, it turns out it's really useful to have more information available in `map`, so let's give those monsters what they want.
=> Pass node to map function

src/mount.js, tests/__snapshots__/mount-deep.test.js.snap, tests/__snapshots__/mount-shallow.test.js.snap, tests/__snapshots__/mount.test.js.snap
It seems like the snapshots where overwritten when updating to Enzyme 3 and React 16.
=> fix: Skip undefined props in snapshots

index.d.ts
Due to the new typing rules of TypeScript 2.6 for functions, one need to specify an overload with generic parameters for `toJson`, `mountToJson` and `shallowToJson`.
=> Add overloads with generic parameters

.prettierrc, src/shallow.js, src/utils.js, tests/__snapshots__/mount.test.js.snap, tests/__snapshots__/render.test.js.snap, tests/__snapshots__/shallow.test.js.snap, tests/fixtures/pure-function.js, tests/mount.test.js, tests/render.test.js, tests/shallow.test.js, yarn.lock
Closes #90 
Hi there, tried my hand at supporting fragments.
Atm I'm just hacking around `typeName` from `enzyme/build/Debug` not supporting fragments. Might be better placed modifying their library to support it - maybe (or maybe not, perhaps it's not something they should do)?
Oh, I've also I added a `.prettierrc` that matches the code base  - let me know what you think.
Cheers!
=> feat(react-fragments): support react fragments

src/shallow.js, tests/__snapshots__/shallow.test.js.snap, tests/fixtures/class.js, tests/fixtures/pure-function.js, tests/shallow.test.js
Closes #55 
Atm I'm checking if the default props exists, and if it has the same value in props, then omit it.
This isn't a perfect solution though - what happens if someone passes down a prop that is the same value as the default prop? Semantically we shouldn't omit it then, but this logic will.
Let me know if you can think of another angle we should take.
=> bugfix(default-props): excludes default props from snapshops in shallow mode

package.json, src/shallow.js, src/utils.js, tests/__snapshots__/shallow.test.js.snap, tests/fixtures/pure-function.js, tests/shallow.test.js, yarn.lock
We needed that, so I decided to implement missing stuff from React 16.6 (at least until Enzyme will not support it in easier/different way)
Added:
- `React.lazy` => resolves to `<React.Lazy>`
- `React.memo` =>  resolves to `<React.Memo>`
- `React.Suspense`=>  resolves to `<React.Suspense>`
Removed/Changed (because of enzyme's update):
- `React.Fragment`  resolves to `<Fragment>` + child fragments are not visible in snapshots
- `Array` => renders differently
=> Add support for Lazy, Memo and Suspense, bump deps

README.md, index.d.ts, src/shallow.js, tests/__snapshots__/shallow.test.js.snap, tests/fixtures/class.js, tests/fixtures/pure-function.js, tests/shallow.test.js
@adriantoine Hi !
I cherry-pick the @madou commit.
I cherry-pick the @jiangzhu-genie commit in [this PR](https://github.com/adriantoine/enzyme-to-json/pull/112)
And then I add an option `ignoreDefaultProps` to add this behaviour.
This way there is no breaking changes. Fixing https://github.com/adriantoine/enzyme-to-json/issues/99
=> Add options to disable default props in snapshot

README.md
according to the [enzyme config documentation](https://jestjs.io/docs/en/configuration.html) setupTestFrameworkScriptFile was deprecated and replaced by [setupFilesAfterEnv](https://jestjs.io/docs/en/configuration.html#setupfilesafterenv-array)
=> change readme from setupTestFrameworkScriptFile to setupFilesAfterEnv

package.json, src/utils.js, tests/utils.test.js, yarn.lock
Closes #137 
Seems that `enzyme-adapter-react-16` was the one that broke the type checks. So this also bumps those versions to make sure the tests passes both before and after the bump.
=> Fix check of node type 

src/render.js, tests/__snapshots__/render.test.js.snap, tests/fixtures/pure-function.js, tests/render.test.js
Hello
Script tags were skipped on the enzyme render() method as their `type` is `script` and not `tag`.
Fixes #133
=> Fix script tags returning null on render

.babelrc, package.json
We are dropping support for Node v4 and Node v5 mainly because [Yarn doesn't support those versions anymore](https://github.com/yarnpkg/yarn/issues/6900) so it's impossible to run tests and make sure our library works with those versions.
You can still use `enzyme-to-json` with Node v4 but we can't make sure it's perfectly working.
=> Dropping support for Node v4 and Node v5

package.json, src/shallow.js, tests/__snapshots__/shallow.test.js.snap, tests/fixtures/forwardRef.js, tests/shallow.test.js, yarn.lock
This PR addresses an issue I found when I wrapped a component in `React.forwardRef` and it's `defaultProps` appeared in my snapshots despite me having `ignoreDefaultProps` set.
To handle this, I've added the `react-is` library which was explicitly developed by the React JS team to handle this sort of type checking more robustly.
I've written tests and ensured that existing tests don't fail.
=> ignoreDefaultProps should work for forwardRef components as well

src/mount.js, tests/__snapshots__/mount-deep.test.js.snap, tests/mount-deep.test.js
When using deep mount on a component wrapped with a forwardRef, currently enzyme-to-json includes the forwardRef node in the JSON.
Running the test included here without the added check for forwardRef results in the following snapshot:
```
<ForwardRef
falsyValue={false}
value="hi mum"
>
<div
className="basic-class undefined"
onClick={[Function]}
>
<div
className="group"
id="group-id"
>
<span />
<span
className="empty"
/>
</div>
</div>
</ForwardRef>
```
Since the deep mode should only include DOM nodes, this PR adds a check to exclude the forwardRef node but include the output of the wrapped component.
=> Exclude forward ref when using deep mount

src/mount.js, tests/__snapshots__/mount-deep.test.js.snap, tests/fixtures/memo.js, tests/mount-deep.test.js, yarn.lock
Similar to this PR: https://github.com/adriantoine/enzyme-to-json/pull/167
We're not currently handling .memo components with deep mount serialization the same way we handle other components.
This addresses that. This results in no diff for deep snapshots when wrapping components in memo.
=> handle deep mounted memo components properly

package.json, yarn.lock
[https://github.com/adriantoine/enzyme-to-json/issues/180](https://github.com/adriantoine/enzyme-to-json/issues/180)
Prototype pollution attack when using _.zipObjectDeep in lodash before 4.17.20. Lodash versions prior to 4.17.21 are vulnerable to Command Injection via the template function.
Lodash versions prior to 4.17.21 are vulnerable to Regular Expression Denial of Service (ReDoS) via the toNumber, trim and trimEnd functions. WhiteSource Note: After conducting further research, WhiteSource has determined that CVE-2020-28500 only affects environments with versions 4.0.0 to 4.17.20 of Lodash.
=> bump lodash from 4.17.15 to 4.17.21 to fix vulnerabilities
